name: Build
on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:
    branches: [main]

permissions:
  contents: write
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.x
      
      - name: Install dependencies
        run: |
          go get -v -t -d ./...
          if [ -f "go.mod" ]; then
            go mod download
          fi
      
      - name: Build
        run: make all
        
      - name: Create release
        if: startsWith(github.ref, 'refs/tags/')
        uses: ncipollo/release-action@v1
        with:
          artifacts: "bin/*"
          artifactErrorsFailBuild: true
          generateReleaseNotes: true
          makeLatest: latest
          tag: ${{ github.ref }}
          name: Release ${{ github.ref }}
          token: ${{ secrets.GITHUB_TOKEN }}